<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="CliOutput.Test" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OutputEngine\OutputEngine.csproj" />
	</ItemGroup>

</Project>
